### ISSUE TITLE
Not able to receive mails

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wild-config#4]
Hi!
Im trying to put toghether a mail server in a centos vps
The server is running correctly as you can see, it says the following

```sh
9|wild     | info IMAP Secure IMAP Server listening on [::]:993
9|wild     | info IMAP IMAP Server listening on [::]:143
9|wild     | info POP3 POP3 Server listening on [::]:110
9|wild     | info LMTP LMTP Server listening on [::]:24
9|wild     | info API Server listening on 127.0.0.1:8080
```

One question... I dont see the SMTP server there but in the default.toml I got it enabled
```toml
[smtp.setup]
# Public configuration for SMTP MDA, needed for mobileconfig files
enabled=true
hostname="localhost"
secure=false
port=25
```

Is there something I'm doing wrong? i have the mx records in my dns set but I'm not getting any mail, I check in the output of the main process and it seems that gmail is not able to connect to the server. Any ideas?

Thanks!
